config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'

  post '/user/ban/:id', to: 'users#ban', as: :ban
  post '/user/unban/:id', to: 'users#unban', as: :unban

  root 'welcome#index'

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth_hash)
    provider = auth_hash[:provider]
    case provider
      when 'vkontakte'
        user = find_or_create_by(vkontakte: auth_hash['info']['urls'][provider.capitalize])
      when 'twitter'
        user = find_or_create_by(twitter: auth_hash['info']['urls'][provider.capitalize])
      when 'facebook'
        user = find_or_create_by(facebook: auth_hash['info']['urls'][provider.capitalize])
    end

    user.username = auth_hash['info']['name']
    user.img_url = auth_hash['info']['image']
    user.last_activity = Time.now
    user.save!
    user
  end

  def self.add_social(auth_hash, user)
    provider = auth_hash[:provider]
    url = auth_hash['info']['urls'][provider.capitalize]
    case provider
      when 'vkontakte'
        useless_user = find_by(vkontakte: url)
        useless_user.destroy
        user.vkontakte = url
      when 'twitter'
        useless_user = find_by(twitter: url)
        useless_user.destroy
        user.twitter = url
      when 'facebook'
        useless_user = find_by(facebook: url)
        useless_user.destroy
        user.facebook = url
    end
    user.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by(id: session[:id])
  end

  helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    begin
      if(current_user)
        User.add_social(request.env['omniauth.auth'], current_user)
      else
        @user = User.from_omniauth(request.env['omniauth.auth'])
        if @user.banned
          flash[:warning] = 'You are banned on this resource'
        else
          session[:id] = @user.id
          flash[:success] = 'Welcome'
        end
      end
    rescue
      flash[:warning] = 'Something bad happened while authenticating'
    end
    redirect_to root_path
  end

  def destroy
    if current_user
      current_user.last_activity = Time.now
      current_user.save!
      session[:id] = -1
      flash[:success] = 'Chiao'
    end
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def ban
    if(current_user&.privileged)
      user = User.find(params[:id])
      user.banned = true
      if(user.save)
        redirect_to users_path
      else
        flash[:warning] = 'Ban failed'
      end
    end
  end

  def unban
    if(current_user&.privileged)
      user = User.find(params[:id])
      user.banned = false
      if(user.save)
        redirect_to users_path
      else
        flash[:warning] = 'Ban failed'
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Check</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar">
        <ul class="nav navbar-nav pull-right">
          <% if current_user %>
            <li><%= image_tag current_user.img_url, alt: current_user.username, class: 'ico' %></li>
            <li><%= link_to 'Logout', logout_path, method: :delete %></li>
          <% else %>
            <li>
              <%= link_to image_tag("twitter.png", alt: 'twitter'), '/auth/twitter', class: 'ico' %>
            </li>
            <li>
              <%= link_to image_tag("vk.png", alt: 'vkontakte'), '/auth/vkontakte', class: 'ico' %>
            </li>
            <li>
              <%= link_to image_tag("facebook.png", alt: 'facebook'), '/auth/facebook', class: 'ico' %>
            </li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav">
          <li>
            <%= link_to 'Users', users_path %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/users/index.html.erb
<table class="table usertable">
  <tr>
    <th>Username</th>
    <th>Avatar</th>
    <th>VK</th>
    <th>Twitter</th>
    <th>Facebook</th>
    <th>Last online</th>
    <% if current_user&.privileged %>
    <th>Control</th>
    <% end %>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= image_tag user.img_url, alt: user.username %></td>
      <td>
        <% if user.vkontakte %>
          <%= link_to 'vk.com', user.vkontakte %>
        <% else %>
          <%=link_to 'Add', '/auth/vkontakte' %>
        <% end %>
      </td>
      <td>
        <% if user.twitter %>
            <%= link_to 'twitter.com', user.twitter %>
        <% else %>
            <%=link_to 'Add', '/auth/twitter' %>
        <% end %>
      </td>
      <td>
        <% if user.facebook %>
            <%= link_to 'facebook.com', user.facebook %>
        <% else %>
            <%=link_to 'Add', '/auth/facebook' %>
        <% end %>
      </td>
      <td><%= user.last_activity %></td>
      <% if current_user&.privileged %>
        <td>
          <% if user.banned %>
              <span class="glyphicon glyphicon-erase"><%= link_to 'Unban', unban_path(user.id), method: :post %></span>
          <% else %>
              <span class="glyphicon glyphicon-ban-circle"><%= link_to 'Ban', ban_path(user.id), method: :post %></span>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/welcome/index.html.erb
<% if current_user %>
    <div class="page-header">
      <h1>A bit of information</h1>
    </div>
    <div class="panel panel-default">
      <div class="panel-body">
        <ul>
          <li><strong>Name:</strong> <%= current_user.username %></li>
          <li><strong>Last activity:</strong> <%= current_user.last_activity %></li>
          <li><strong>Avatar URL:</strong> <%= current_user.img_url %></li>
          <li><strong>VK:</strong> <%= current_user.vkontakte %></li>
          <li><strong>Twitter:</strong> <%= current_user.twitter %></li>
          <li><strong>Facebook:</strong> <%= current_user.facebook %></li>
        </ul>
      </div>
    </div>
<% else %>
    <div class="jumbotron">
      <h2>Welcome</h2>
      <p>Please authorize with one of social networks in top right corner</p>
    </div>
<% end %>